name: Deploy Azure SQL Database

on:
  push:
    branches:
      - main

env:
  SQL_SERVER: "sql-srv-jerson-lab03.database.windows.net"
  SQL_DATABASE: "adventureworkslt-db-jerson"
  RESOURCE_GROUP: "lab03-sql-rg-jerson"  # Reemplaza con tu grupo de recursos real

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Login to Azure
      run: |
        az login --service-principal \
          -u ${{ secrets.AZURE_CLIENT_ID }} \
          -p ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Get GitHub Runner IP
      id: ip
      run: |
        RUNNER_IP=$(curl -s https://api.ipify.org)
        echo "::set-output name=runner_ip::$RUNNER_IP"

    - name: Configure Azure SQL Firewall
      run: |
        az sql server firewall-rule create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --server sql-srv-jerson-lab03 \
          --name "GitHubActions-${{ github.run_id }}" \
          --start-ip-address "${{ steps.ip.outputs.runner_ip }}" \
          --end-ip-address "${{ steps.ip.outputs.runner_ip }}"
        
        # Esperar para asegurar que la regla esté activa
        sleep 30

    - name: Install sqlcmd
      run: |
        curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl -sSL https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev

    - name: Run SQL Script
      env:
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      run: |
        /opt/mssql-tools/bin/sqlcmd -S ${{ env.SQL_SERVER }} -d ${{ env.SQL_DATABASE }} \
          -U $SQL_USER -P $SQL_PASSWORD -i bd.sql

    - name: Clean up firewall rule
      if: always()
      run: |
        az sql server firewall-rule delete \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --server sql-srv-jerson-lab03 \
          --name "GitHubActions-${{ github.run_id }}" \
          --yes