name: Deploy Azure SQL DB (Final Fix for Lab03)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Clean Existing Resources (Optional)
        run: |
          az sql server firewall-rule delete \
            --resource-group lab03-sql-rg-jerson \
            --server sql-srv-jerson-lab03 \
            --name "Allow-GitHub-Actions" \
            --yes || true
        continue-on-error: true

      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: infra

      - name: Import All Resources
        run: |
          terraform import azurerm_resource_group.rg /subscriptions/37b22429-d75b-401b-a09c-de8a04575609/resourceGroups/lab03-sql-rg-jerson || true
          terraform import azurerm_mssql_server.sql_server /subscriptions/37b22429-d75b-401b-a09c-de8a04575609/resourceGroups/lab03-sql-rg-jerson/providers/Microsoft.Sql/servers/sql-srv-jerson-lab03 || true
          terraform import azurerm_mssql_database.sql_db /subscriptions/37b22429-d75b-401b-a09c-de8a04575609/resourceGroups/lab03-sql-rg-jerson/providers/Microsoft.Sql/servers/sql-srv-jerson-lab03/databases/adventureworkslt-db-jerson || true
          terraform refresh
        working-directory: infra

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
        working-directory: infra

      - name: Add GitHub Actions IP to Azure SQL Firewall
        run: |
          az sql server firewall-rule create \
            --resource-group lab03-sql-rg-jerson \
            --server sql-srv-jerson-lab03 \
            --name Allow-GitHub-Actions \
            --start-ip-address 0.0.0.0 \
            --end-ip-address 0.0.0.0

      - name: Restore Database from .bak
        run: |
          # Subir el archivo .bak a un contenedor de Azure Blob Storage
          az storage blob upload \
            --account-name <cuentaalmacenamiento3> \
            --container-name <backups> \
            --file AdventureWorksLT2016.bak \
            --name AdventureWorksLT2016.bak

          # Restaurar la base de datos desde el archivo .bak
          az sql db restore \
            --resource-group lab03-sql-rg-jerson \
            --server sql-srv-jerson-lab03 \
            --destination-database adventureworkslt-db-jerson \
            --backup-storage-redundancy LRS \
            --name AdventureWorksLT2016 \
            --source-database adventureworkslt-db-jerson \
            --blob-url https://<storage-account-name>.blob.core.windows.net/<container-name>/AdventureWorksLT2016.bak
