name: Deploy Azure SQL DB (Final Fix for Lab03)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Clean Existing Resources (Optional)
        run: |
          az sql server firewall-rule delete \
            --resource-group lab03-sql-rg-jerson \
            --server sql-srv-jerson-lab03 \
            --name "Allow-GitHub-Actions" \
            --yes || true
        continue-on-error: true

      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: infra

      - name: Import All Resources
        run: |
          terraform import azurerm_resource_group.rg /subscriptions/37b22429-d75b-401b-a09c-de8a04575609/resourceGroups/lab03-sql-rg-jerson || true
          terraform import azurerm_mssql_server.sql_server /subscriptions/37b22429-d75b-401b-a09c-de8a04575609/resourceGroups/lab03-sql-rg-jerson/providers/Microsoft.Sql/servers/sql-srv-jerson-lab03 || true
          terraform import azurerm_mssql_database.sql_db /subscriptions/37b22429-d75b-401b-a09c-de8a04575609/resourceGroups/lab03-sql-rg-jerson/providers/Microsoft.Sql/servers/sql-srv-jerson-lab03/databases/adventureworkslt-db-jerson || true
          terraform refresh
        working-directory: infra

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
        working-directory: infra

      - name: Add GitHub Actions IP to Azure SQL Firewall
        run: |
          az sql server firewall-rule create \
            --resource-group lab03-sql-rg-jerson \
            --server sql-srv-jerson-lab03 \
            --name Allow-GitHub-Actions \
            --start-ip-address 0.0.0.0 \
            --end-ip-address 0.0.0.0

            - name: Install sqlcmd
            run: |
              curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
              curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
              sudo apt-get update
              sudo apt-get install -y mssql-tools unixodbc-dev
              # Asegúrate de agregar sqlcmd al PATH en la sesión actual
              echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
              source ~/.bashrc
          
      - name: Restore from .bak using sqlcmd
        run: |
              sqlcmd -S sql-srv-jerson-lab03.database.windows.net \
                     -U "sqladmin" \
                     -P "${{ secrets.SQL_ADMIN_PASSWORD }}" \
                     -d master \
                     -Q "RESTORE DATABASE [adventureworkslt-db-jerson] FROM URL = 'https://cuentaalmacenamiento3.blob.core.windows.net/backups/AdventureWorksLT2016.bak' WITH CREDENTIAL = 'AzureStorageCredential', STATS = 5, REPLACE"