name: Deploy Azure SQL Database

on:
  push:
    branches:
      - main  # o la rama donde trabajes

jobs:
  deploy-db:
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/mssql-tools  # Usa la imagen oficial que trae sqlcmd

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Run SQL Script to Create AdventureWorksLT
      env:
        SQL_SERVER: "sql-srv-jerson-lab03.database.windows.net"
        SQL_DATABASE: "adventureworkslt-db-jerson"
        SQL_USER: "sqladmin"
        SQL_PASSWORD: "P@ssw0rd1234!"
      run: |
        sqlcmd -S $SQL_SERVER -d $SQL_DATABASE -U $SQL_USER -P $SQL_PASSWORD -i bd.sql
